name: Cache example

on: push

jobs:
  caching:
    runs-on: ubuntu-latest
    steps:
      - name: Loading
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4.0.2
        id: cache
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: README.md
          key: ${{ runner.os }}-${{ hashFiles( README.md ) }}

      - name: No cache hit
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "No cache hit"

      - name: Yes cache hit
        if: steps.cache.outputs.cache-hit == 'true'
        run: echo "Yes cache hit"
